Project: Project_Settings/Startup_Code/__arm_start.c File Reference
__arm_start.c File Reference
#include <string.h>
#include <stdlib.h>
#include <runtime_configuration.h>
Functions
void __call_static_initializers (void)
int main (int, char **)
void __init_registers ()
void __init_hardware ()
void __init_user ()
static void zero_fill_bss (void)
void __iar_program_start (void)
void __thumb_startup (void)
Variables
static _EWL_BEGIN_EXTERN_C char * argv [] = { 0 }
Function Documentation
void __call_static_initializers (void)
Referenced by __thumb_startup().
void __iar_program_start (void)
Definition at line 155 of file __arm_start.c.
References __thumb_startup().
void __init_hardware ()
===========================================================================
Reset handler
Definition at line 42 of file kinetis_sysinit.c.
Referenced by __thumb_startup().
void __init_registers ()
Referenced by __thumb_startup().
void __init_user ()
Referenced by __thumb_startup().
void __thumb_startup (void)
Definition at line 171 of file __arm_start.c.
References __call_static_initializers(), __init_hardware(), __init_registers(), __init_user(), argv, main(), and zero_fill_bss().
Referenced by __iar_program_start(), and NMI_Handler().
int main (int , char **)
Referenced by __thumb_startup().
static void zero_fill_bss (void) static
Definition at line 129 of file __arm_start.c.
Referenced by __thumb_startup().
Variable Documentation
_EWL_BEGIN_EXTERN_C char* argv[] = { 0 } static
Definition at line 45 of file __arm_start.c.
Referenced by __thumb_startup().