Project: Sources/HAL/GPIO.h File Reference
GPIO.h File Reference
Archivo header de GPIO.
#include "derivative.h"
#include "Types.h"
Macros
#define ALTERNATIVE1 1
Functions
void vfnCfgRainSensorGPIO (void)
Configurar el puerto B0 para el sensor de lluvia.
U08 u08CheckBit (U08 u08Bit)
void vfnTogglePinE (U08 u08pinToToggle)
void vfnCfgPorts (void)
Sirve para configurar el reloj de los puertos.
void vfnPortPCR (U08 u08Base, U08 u08Alternative, U08 u08Pin)
void vfnTooglePinX (U08 u08pinToToggle, U08 u08Base)
void vfnCfgLedPorts (void)
Sirve para la configurar los pines como salida (Leds)
void vfnTurnOnRedLed (void)
Sirve para prender el Led rojo del pin 18.
void vfnToggleGreenLed (void)
Sirve para hacer un Toogle el Led verde del pin 19.
void vfnToggleRedLed (void)
Sirve para hacer un Toogle el Led rojo del pin 18.
void vfnTogglePin (U08 u08pinToToggle)
Detailed Description
Archivo header de GPIO.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file GPIO.h.
Macro Definition Documentation
#define ALTERNATIVE1 1
Definition at line 29 of file GPIO.h.
Referenced by vfnCfgLedPorts(), and vfnCfgRainSensorGPIO().
Function Documentation
U08 u08CheckBit (U08 u08Bit)
Definition at line 121 of file GPIO.c.
References GPIO_PDIR_PDI, and GPIOB_PDIR.
Referenced by vfnIsRaining().
void vfnCfgLedPorts (void)
Sirve para la configurar los pines como salida (Leds)
Parameters
Definition at line 143 of file GPIO.c.
References ALTERNATIVE1, GPIO_PDDR_PDD, GPIO_PDOR_PDO, GPIOB_PDDR, GPIOB_PDOR, GPIOD_PDDR, GPIOD_PDOR, GPIOE_PDDR, GPIOE_PDOR, PORT_PCR_MUX, PORTB_PCR18, PORTB_PCR19, PORTD_PCR1, PORTE_PCR0, PORTE_PCR1, and PORTE_PCR2.
Referenced by main().
void vfnCfgPorts (void)
Sirve para configurar el reloj de los puertos.
Parameters
u08pinToToggle
Returns
Definition at line 66 of file GPIO.c.
References SIM_SCGC5, SIM_SCGC5_PORTA_MASK, SIM_SCGC5_PORTB_MASK, SIM_SCGC5_PORTC_MASK, SIM_SCGC5_PORTD_MASK, and SIM_SCGC5_PORTE_MASK.
Referenced by main().
void vfnCfgRainSensorGPIO (void)
Configurar el puerto B0 para el sensor de lluvia.
Parameters
Definition at line 111 of file GPIO.c.
References ALTERNATIVE1, PORT_PCR_MUX, and PORTB_PCR0.
void vfnPortPCR (U08 u08Base, U08 u08Alternative, U08 u08Pin)
Definition at line 132 of file GPIO.c.
References PORT_PCR_MUX, and PORT_PCR_REG.
Referenced by cfgPWM(), and vfnCfgRainSensorPorts().
void vfnToggleGreenLed (void)
Sirve para hacer un Toogle el Led verde del pin 19.
Parameters
Definition at line 192 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
void vfnTogglePin (U08 u08pinToToggle)
Definition at line 80 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
void vfnTogglePinE (U08 u08pinToToggle)
Definition at line 90 of file GPIO.c.
References GPIO_PDOR_PDO, GPIO_PDOR_REG, and PTE_BASE_PTR.
void vfnToggleRedLed (void)
Sirve para hacer un Toogle el Led rojo del pin 18.
Parameters
Definition at line 182 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
Referenced by vfnBTState0().
void vfnTooglePinX (U08 u08pinToToggle, U08 u08Base)
Definition at line 101 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIO_PDOR_REG.
Referenced by vfnBTState1().
void vfnTurnOnRedLed (void)
Sirve para prender el Led rojo del pin 18.
Parameters
Definition at line 172 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.