Project: Sources/HAL/GPIO.c File Reference
GPIO.c File Reference
Archivo main de GPIO.
#include "GPIO.h"
Functions
void vfnCfgPorts (void)
Sirve para configurar el reloj de los puertos.
void vfnTogglePin (U08 u08pinToToggle)
void vfnTogglePinE (U08 u08pinToToggle)
void vfnTooglePinX (U08 u08pinToToggle, U08 u08Base)
void vfnCfgRainSensorGPIO (void)
Configurar el puerto B0 para el sensor de lluvia.
U08 u08CheckBit (U08 u08Bit)
void vfnPortPCR (U08 u08Base, U08 u08Alternative, U08 u08Pin)
void vfnCfgLedPorts (void)
Sirve para la configurar los pines como salida (Leds)
void vfnTurnOnRedLed (void)
Sirve para prender el Led rojo del pin 18.
void vfnToggleRedLed (void)
Sirve para hacer un Toogle el Led rojo del pin 18.
void vfnToggleGreenLed (void)
Sirve para hacer un Toogle el Led verde del pin 19.
Variables
const unsigned int MASKSIM [] = {SIM_SCGC5_PORTA_MASK,SIM_SCGC5_PORTB_MASK,SIM_SCGC5_PORTC_MASK,SIM_SCGC5_PORTD_MASK,SIM_SCGC5_PORTE_MASK}
Arreglo para activar el reloj de los puertos.
const PORT_MemMapPtr MASKBASE [] = {PORTA_BASE_PTR,PORTB_BASE_PTR,PORTC_BASE_PTR,PORTD_BASE_PTR,PORTE_BASE_PTR}
Arreglo para establecer modo de los puertos.
const GPIO_MemMapPtr MASKDIR [] = {PTA_BASE_PTR,PTB_BASE_PTR,PTC_BASE_PTR,PTD_BASE_PTR,PTE_BASE_PTR}
Arreglo para seleccionar el puerto donde se van a enviar datos.
Detailed Description
Archivo main de GPIO.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file GPIO.c.
Function Documentation
U08 u08CheckBit (U08 u08Bit)
Definition at line 121 of file GPIO.c.
References GPIO_PDIR_PDI, and GPIOB_PDIR.
Referenced by vfnIsRaining().
vfnCfgLedPorts (void)
Sirve para la configurar los pines como salida (Leds)
Parameters
Definition at line 143 of file GPIO.c.
References ALTERNATIVE1, GPIO_PDDR_PDD, GPIO_PDOR_PDO, GPIOB_PDDR, GPIOB_PDOR, GPIOD_PDDR, GPIOD_PDOR, GPIOE_PDDR, GPIOE_PDOR, PORT_PCR_MUX, PORTB_PCR18, PORTB_PCR19, PORTD_PCR1, PORTE_PCR0, PORTE_PCR1, and PORTE_PCR2.
Referenced by main().
vfnCfgPorts (void)
Sirve para configurar el reloj de los puertos.
Parameters
u08pinToToggle
Returns
Definition at line 66 of file GPIO.c.
References SIM_SCGC5, SIM_SCGC5_PORTA_MASK, SIM_SCGC5_PORTB_MASK, SIM_SCGC5_PORTC_MASK, SIM_SCGC5_PORTD_MASK, and SIM_SCGC5_PORTE_MASK.
Referenced by main().
vfnCfgRainSensorGPIO (void)
Configurar el puerto B0 para el sensor de lluvia.
Parameters
Definition at line 111 of file GPIO.c.
References ALTERNATIVE1, PORT_PCR_MUX, and PORTB_PCR0.
void vfnPortPCR (U08 u08Base, U08 u08Alternative, U08 u08Pin)
Definition at line 132 of file GPIO.c.
References PORT_PCR_MUX, and PORT_PCR_REG.
Referenced by cfgPWM(), and vfnCfgRainSensorPorts().
vfnToggleGreenLed (void)
Sirve para hacer un Toogle el Led verde del pin 19.
Parameters
Definition at line 192 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
void vfnTogglePin (U08 u08pinToToggle)
Definition at line 80 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
void vfnTogglePinE (U08 u08pinToToggle)
Definition at line 90 of file GPIO.c.
References GPIO_PDOR_PDO, GPIO_PDOR_REG, and PTE_BASE_PTR.
vfnToggleRedLed (void)
Sirve para hacer un Toogle el Led rojo del pin 18.
Parameters
Definition at line 182 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
Referenced by vfnBTState0().
void vfnTooglePinX (U08 u08pinToToggle, U08 u08Base)
Definition at line 101 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIO_PDOR_REG.
Referenced by vfnBTState1().
vfnTurnOnRedLed (void)
Sirve para prender el Led rojo del pin 18.
Parameters
Definition at line 172 of file GPIO.c.
References GPIO_PDOR_PDO, and GPIOB_PDOR.
Variable Documentation
MASKBASE = {PORTA_BASE_PTR,PORTB_BASE_PTR,PORTC_BASE_PTR,PORTD_BASE_PTR,PORTE_BASE_PTR}
Arreglo para establecer modo de los puertos.
Definition at line 50 of file GPIO.c.
MASKDIR = {PTA_BASE_PTR,PTB_BASE_PTR,PTC_BASE_PTR,PTD_BASE_PTR,PTE_BASE_PTR}
Arreglo para seleccionar el puerto donde se van a enviar datos.
Definition at line 58 of file GPIO.c.
MASKSIM = {SIM_SCGC5_PORTA_MASK,SIM_SCGC5_PORTB_MASK,SIM_SCGC5_PORTC_MASK,SIM_SCGC5_PORTD_MASK,SIM_SCGC5_PORTE_MASK}
Arreglo para activar el reloj de los puertos.
Definition at line 44 of file GPIO.c.