Project: Sources/APP/MainTemplate.c File Reference
MainTemplate.c File Reference
Archivo main.
#include "derivative.h"
#include "RainSensor.h"
#include "PWM.h"
#include "UART.h"
#include "GPIO.h"
#include "Types.h"
Macros
#define AUTO 1
Poner el mode de la aplicacion en Automatico.
#define MANUAL 0
Poner el mode de la aplicacion en Manual.
Enumerations
enum eBTSTATES { eSTATE0 = 0, eSTATE1, eSTATE2, eRESET }
Enumeracion para la maquina de estados de la aplicacion.
Functions
void vfnBTState0 (void)
Estado 0 de la maquina de estados donde se recibe el caracter y se manda al siguiente estado dependiendo la condicion.
void vfnBTState1 (void)
Estado 1 de la maquina de estados donde se recibe el caracter y se manda al siguiente estado dependiendo la condicion.
void vfnBTState2 (void)
void vfnBTStateReset (void)
Estado de la maquina de estados donde se hace el reset y manda al primer estado.
void vfnRSState0 (void)
Estado 0 de la maquina de estados donde se manda al siguiente estado dependiendo la condicion.
void vfnRSState1 (void)
Estado 1 de la maquina de estados donde se cambia el valor del TPM0_COV para el movimiento del Servomotor.
void vfnRSState2 (void)
Estado 2 de la maquina de estados donde se checa si el sensor de lluvia detecta lluvia y cambia el TPM0_COV para el movimiento del Servomotor.
void vfnRSStateReset (void)
Estado de la maquina de estados donde se hace el reset y manda al primer estado.
int main (void)
Variables
eBTSTATES u08BTStateValue = eSTATE0
Variable para almacenar el estado actual de la maquina de estados del Bluetooth.
eBTSTATES u08RSStateValue = eSTATE0
U08 u08UART_D
Variable para almacenar lo que se recibe de UART.
U08 u08AutoMode = AUTO
Variable inicializar el modo en Automatico.
void(* vfnBTMachineState [])(void) = { vfnBTState0, vfnBTState1, vfnBTState2, vfnBTStateReset }
Arreglo de Apuntadores a funciones de la maquina de estados del Bluetooth.
void(* vfnRSMachineState [])(void) = { vfnRSState0, vfnRSState1, vfnRSState2, vfnRSStateReset }
Arreglo de Apuntadores a funciones de la maquina de estados del Sensor de Lluvia.
static volatile U08 u08PortSelected
Guarda el valor del puerto seleccionado.
Detailed Description
Archivo main.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file MainTemplate.c.
Macro Definition Documentation
#define AUTO 1
Poner el mode de la aplicacion en Automatico.
Definition at line 30 of file MainTemplate.c.
Referenced by vfnBTState0(), vfnBTState1(), and vfnRSState0().
#define MANUAL 0
Poner el mode de la aplicacion en Manual.
Definition at line 36 of file MainTemplate.c.
Referenced by vfnBTState0(), vfnBTState1(), and vfnRSState0().
Enumeration Type Documentation
enum eBTSTATES
Enumeracion para la maquina de estados de la aplicacion.
Enumerator
eSTATE0
eSTATE1
eSTATE2
eRESET
Definition at line 44 of file MainTemplate.c.
Function Documentation
int main (void)
Definition at line 104 of file MainTemplate.c.
References cfgPWM(), eRESET, u08BTStateValue, u08RSStateValue, vfnBTMachineState, vfnCfgLedPorts(), vfnCfgPorts(), vfnCfgRainSensorPorts(), vfnCfgUART0(), and vfnRSMachineState.
void vfnBTState0 (void)
Estado 0 de la maquina de estados donde se recibe el caracter y se manda al siguiente estado dependiendo la condicion.
Parameters
Definition at line 128 of file MainTemplate.c.
References AUTO, eSTATE1, MANUAL, u08AutoMode, u08BTStateValue, u08PortSelected, u08UART_D, uart0_getchar(), vfnToggleRedLed(), and vfnTPM0ChannelValue().
void vfnBTState1 (void)
Estado 1 de la maquina de estados donde se recibe el caracter y se manda al siguiente estado dependiendo la condicion.
Parameters
Definition at line 160 of file MainTemplate.c.
References AUTO, eRESET, MANUAL, u08AutoMode, u08BTStateValue, u08PortSelected, u08UART_D, uart0_getchar(), vfnTooglePinX(), and vfnTPM0ChannelValue().
void vfnBTState2 (void)
Parameters
Definition at line 192 of file MainTemplate.c.
void vfnBTStateReset (void)
Estado de la maquina de estados donde se hace el reset y manda al primer estado.
Parameters
Definition at line 201 of file MainTemplate.c.
References eSTATE0, and u08BTStateValue.
void vfnRSState0 (void)
Estado 0 de la maquina de estados donde se manda al siguiente estado dependiendo la condicion.
Parameters
Definition at line 211 of file MainTemplate.c.
References AUTO, eSTATE1, eSTATE2, MANUAL, u08AutoMode, and u08RSStateValue.
void vfnRSState1 (void)
Estado 1 de la maquina de estados donde se cambia el valor del TPM0_COV para el movimiento del Servomotor.
Parameters
Definition at line 229 of file MainTemplate.c.
References eRESET, u08RSStateValue, vfnIsRaining(), and vfnTPM0ChannelValue().
void vfnRSState2 (void)
Estado 2 de la maquina de estados donde se checa si el sensor de lluvia detecta lluvia y cambia el TPM0_COV para el movimiento del Servomotor.
Parameters
Definition at line 249 of file MainTemplate.c.
References eRESET, u08RSStateValue, vfnIsRaining(), and vfnTPM0ChannelValue().
void vfnRSStateReset (void)
Estado de la maquina de estados donde se hace el reset y manda al primer estado.
Parameters
Definition at line 266 of file MainTemplate.c.
References eSTATE0, and u08RSStateValue.
Variable Documentation
u08AutoMode = AUTO
Variable inicializar el modo en Automatico.
Definition at line 83 of file MainTemplate.c.
Referenced by vfnBTState0(), vfnBTState1(), and vfnRSState0().
u08BTStateValue = eSTATE0
Variable para almacenar el estado actual de la maquina de estados del Bluetooth.
Variable para almacenar el estado actual de la maquina de estados del Sensor de Lluvia.
Definition at line 68 of file MainTemplate.c.
Referenced by main(), vfnBTState0(), vfnBTState1(), and vfnBTStateReset().
u08PortSelected static
Guarda el valor del puerto seleccionado.
Definition at line 98 of file MainTemplate.c.
Referenced by vfnBTState0(), and vfnBTState1().
eBTSTATES u08RSStateValue = eSTATE0
Definition at line 73 of file MainTemplate.c.
Referenced by main(), vfnRSState0(), vfnRSState1(), vfnRSState2(), and vfnRSStateReset().
u08UART_D
Variable para almacenar lo que se recibe de UART.
Definition at line 78 of file MainTemplate.c.
Referenced by vfnBTState0(), and vfnBTState1().
vfnBTMachineState = { vfnBTState0, vfnBTState1, vfnBTState2, vfnBTStateReset }
Arreglo de Apuntadores a funciones de la maquina de estados del Bluetooth.
Definition at line 88 of file MainTemplate.c.
Referenced by main().
vfnRSMachineState = { vfnRSState0, vfnRSState1, vfnRSState2, vfnRSStateReset }
Arreglo de Apuntadores a funciones de la maquina de estados del Sensor de Lluvia.
Definition at line 93 of file MainTemplate.c.
Referenced by main().