Project: Sources/HAL/PWM.h File Reference
PWM.h File Reference
Archivo header de PWM.
#include "derivative.h"
#include "Types.h"
Macros
#define MCGFLLCLK 1
Functions
void cfgPWM (void)
Configuracion del PWM -con los reloj y el modo en que va funcionar.
void vfnTPM0ChannelValue (U32 u32Value)
Detailed Description
Archivo header de PWM.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file PWM.h.
Macro Definition Documentation
#define MCGFLLCLK 1
Definition at line 29 of file PWM.h.
Referenced by cfgPWM(), and vfnCfgUART0().
Function Documentation
void cfgPWM (void)
Configuracion del PWM -con los reloj y el modo en que va funcionar.
Parameters
Definition at line 53 of file PWM.c.
References MCGFLLCLK, SIM_SCGC6, SIM_SCGC6_TPM0_MASK, SIM_SOPT2, SIM_SOPT2_PLLFLLSEL_MASK, SIM_SOPT2_TPMSRC, TPM0_C0SC, TPM0_CNT, TPM0_MOD, TPM0_SC, and vfnPortPCR().
Referenced by main().
void vfnTPM0ChannelValue (U32 u32Value)
Definition at line 79 of file PWM.c.
References TPM0_C0V.
Referenced by vfnBTState0(), vfnBTState1(), vfnRSState1(), and vfnRSState2().