Project: Sources/HIL/RainSensor.h File Reference
RainSensor.h File Reference
Archivo main de UART.
#include "derivative.h"
#include "Types.h"
#include "GPIO.h"
Macros
#define ALTERNATIVE1 1
#define PORTB0 0
Functions
void vfnCfgRainSensorPorts (void)
Configura los puertos que se van a utilizar en el sensor de lluvia.
U08 vfnIsRaining (void)
Sirve para checar el estado del sensor de lluvia.
Detailed Description
Archivo main de UART.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file RainSensor.h.
Macro Definition Documentation
#define ALTERNATIVE1 1
Definition at line 31 of file RainSensor.h.
#define PORTB0 0
Definition at line 36 of file RainSensor.h.
Referenced by vfnIsRaining().
Function Documentation
void vfnCfgRainSensorPorts (void)
Configura los puertos que se van a utilizar en el sensor de lluvia.
Parameters
Definition at line 52 of file RainSensor.c.
References vfnPortPCR().
Referenced by main().
U08 vfnIsRaining (void)
Sirve para checar el estado del sensor de lluvia.
Parameters
Definition at line 62 of file RainSensor.c.
References PORTB0, and u08CheckBit().
Referenced by vfnRSState1(), and vfnRSState2().