Project: Sources/HIL/RainSensor.c File Reference
RainSensor.c File Reference
Archivo main de RainSensor.
#include "RainSensor.h"
#include "GPIO.h"
Functions
void vfnCfgRainSensorPorts (void)
Configura los puertos que se van a utilizar en el sensor de lluvia.
U08 vfnIsRaining (void)
Sirve para checar el estado del sensor de lluvia.
Detailed Description
Archivo main de RainSensor.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file RainSensor.c.
Function Documentation
vfnCfgRainSensorPorts (void)
Configura los puertos que se van a utilizar en el sensor de lluvia.
Parameters
Definition at line 52 of file RainSensor.c.
References vfnPortPCR().
Referenced by main().
vfnIsRaining (void)
Sirve para checar el estado del sensor de lluvia.
Parameters
Definition at line 62 of file RainSensor.c.
References PORTB0, and u08CheckBit().
Referenced by vfnRSState1(), and vfnRSState2().