Project: Sources/HAL/UART.h File Reference
UART.h File Reference
Archivo Header de UART.
#include "derivative.h"
#include "Types.h"
Macros
#define ALTERNATIVE2 2
#define DEFAULT 0x00
#define MCGFLLCLK 1
#define MCGIRCLK 4
#define BAUD_RATE 546
#define OVER_SAMPLING 3
Functions
void vfnCfgUART0 (void)
Configuracion de los puertos para UART.
U08 u08UART_RxBuffer (void)
Sirve para alamcenar el valor que se recibe por UART.
void vfnUART0_IRQHandler (void)
unsigned char uart0_getchar (void)
Sirve para recibir el valor que es mandado.
Detailed Description
Archivo Header de UART.
Author
Alan Sanchez y Alberto Bautista
Date
13/Abril/2016 History: 20160414_1930 :
Definition in file UART.h.
Macro Definition Documentation
#define ALTERNATIVE2 2
Definition at line 30 of file UART.h.
Referenced by vfnCfgUART0().
#define BAUD_RATE 546
Definition at line 50 of file UART.h.
Referenced by vfnCfgUART0().
#define DEFAULT 0x00
Definition at line 35 of file UART.h.
Referenced by vfnCfgUART0().
#define MCGFLLCLK 1
Definition at line 40 of file UART.h.
#define MCGIRCLK 4
Definition at line 45 of file UART.h.
Referenced by vfnCfgUART0().
#define OVER_SAMPLING 3
Definition at line 55 of file UART.h.
Referenced by vfnCfgUART0().
Function Documentation
U08 u08UART_RxBuffer (void)
Sirve para alamcenar el valor que se recibe por UART.
Parameters
Definition at line 87 of file UART.c.
References UART_gbRxData.
unsigned char uart0_getchar (void)
Sirve para recibir el valor que es mandado.
Parameters
Definition at line 97 of file UART.c.
References UART0_D, UART0_S1, and UART_S1_RDRF_MASK.
Referenced by vfnBTState0(), and vfnBTState1().
void vfnCfgUART0 (void)
Configuracion de los puertos para UART.
Parameters
Definition at line 52 of file UART.c.
References ALTERNATIVE2, BAUD_RATE, DEFAULT, MCGFLLCLK, MCGIRCLK, OVER_SAMPLING, PORT_PCR_MUX, PORTA_PCR1, PORTA_PCR2, SIM_SCGC4, SIM_SCGC4_UART0_MASK, SIM_SCGC5, SIM_SCGC5_PORTA_MASK, SIM_SOPT2, SIM_SOPT2_CLKOUTSEL, SIM_SOPT2_UART0SRC, UART0_BDH, UART0_BDH_SBR_MASK, UART0_BDL, UART0_BDL_SBR_MASK, UART0_C1, UART0_C2, UART0_C2_RE_MASK, UART0_C2_TE_MASK, UART0_C3, UART0_C4, UART0_C4_OSR_MASK, UART0_C5, UART0_C5_BOTHEDGE_MASK, and UART0_S2.
Referenced by main().
void vfnUART0_IRQHandler (void)
Parameters
Definition at line 111 of file UART.c.
References UART0_D, UART0_S1, UART_gbRxData, and UART_S1_RDRF_MASK.